apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: itop-conf-pvc
spec:
  accessModes:
    - {{ .Values.pvc.accessMode }}
  storageClassName: {{ .Values.pvc.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.pvc.conf.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: itop-data-pvc
spec:
  accessModes:
    - {{ .Values.pvc.accessMode }}
  storageClassName: {{ .Values.pvc.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.pvc.data.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: itop-env-pvc
spec:
  accessModes:
    - {{ .Values.pvc.accessMode }}
  storageClassName: {{ .Values.pvc.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.pvc.env.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: itop-log-pvc
spec:
  accessModes:
    - {{ .Values.pvc.accessMode }}
  storageClassName: {{ .Values.pvc.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.pvc.log.size }}
