{{- if .Values.pvc.enabled }}
{{- if .Values.pvc.useOnePV }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: itop-pv
  annotations: {{- .Values.pvc.commonAnnotations | toYaml | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.pvc.accessMode }}
  {{- if  .Values.pvc.storageClassName }}
  storageClassName: {{ .Values.pvc.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.pvc.data.size }}
{{- else }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: itop-conf-pvc
  annotations: {{- .Values.pvc.commonAnnotations | toYaml | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.pvc.accessMode }}
  {{- if  .Values.pvc.storageClassName }}
  storageClassName: {{ .Values.pvc.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.pvc.conf.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: itop-data-pvc
  annotations: {{- .Values.pvc.commonAnnotations | toYaml | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.pvc.accessMode }}
  {{- if  .Values.pvc.storageClassName }}
  storageClassName: {{ .Values.pvc.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.pvc.data.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: itop-env-pvc
  annotations: {{- .Values.pvc.commonAnnotations | toYaml | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.pvc.accessMode }}
  {{- if  .Values.pvc.storageClassName }}
  storageClassName: {{ .Values.pvc.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.pvc.env.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: itop-log-pvc
  annotations: {{- .Values.pvc.commonAnnotations | toYaml | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.pvc.accessMode }}
  {{- if  .Values.pvc.storageClassName }}
  storageClassName: {{ .Values.pvc.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.pvc.log.size }}
apiVersion: v1

{{- if .Values.pvc.extensions.enabled }}
---
kind: PersistentVolumeClaim
metadata:
  name: itop-extensions-pvc
  annotations: {{- .Values.pvc.commonAnnotations | toYaml | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.pvc.accessMode }}
  {{- if  .Values.pvc.storageClassName }}
  storageClassName: {{ .Values.pvc.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.pvc.extensions.size }}
{{- end }}
{{- end }}
{{- end }}
