#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php "$@"
fi

# show iTop log messages in docker logs
tail -F log/setup.log log/error.log log/deadlocks.log log/deprecated-calls.log log/tools.log log/itop-fence.log > /dev/stderr &

exec "$@"
